/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface YetiField {
        "errorMessage": string;
        "inputId": string;
        "inputValue": string;
        "isValid": boolean;
        "label": string;
        "required": boolean;
        "tip": string;
        "value": string;
    }
    interface YetiFormField {
        "htmlId": string;
        "inputTip": string;
        "label": string;
        "required": boolean;
        "value": string;
    }
    interface YetiInput {
        "inputClass": string;
        "inputId": string;
        "inputValue": string;
        "isValid": boolean;
    }
}
export interface YetiInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLYetiInputElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLYetiFieldElement extends Components.YetiField, HTMLStencilElement {
    }
    var HTMLYetiFieldElement: {
        prototype: HTMLYetiFieldElement;
        new (): HTMLYetiFieldElement;
    };
    interface HTMLYetiFormFieldElement extends Components.YetiFormField, HTMLStencilElement {
    }
    var HTMLYetiFormFieldElement: {
        prototype: HTMLYetiFormFieldElement;
        new (): HTMLYetiFormFieldElement;
    };
    interface HTMLYetiInputElement extends Components.YetiInput, HTMLStencilElement {
    }
    var HTMLYetiInputElement: {
        prototype: HTMLYetiInputElement;
        new (): HTMLYetiInputElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "yeti-field": HTMLYetiFieldElement;
        "yeti-form-field": HTMLYetiFormFieldElement;
        "yeti-input": HTMLYetiInputElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface YetiField {
        "errorMessage"?: string;
        "inputId"?: string;
        "inputValue"?: string;
        "isValid"?: boolean;
        "label": string;
        "required"?: boolean;
        "tip"?: string;
        "value"?: string;
    }
    interface YetiFormField {
        "htmlId"?: string;
        "inputTip"?: string;
        "label"?: string;
        "required"?: boolean;
        "value"?: string;
    }
    interface YetiInput {
        "inputClass"?: string;
        "inputId"?: string;
        "inputValue"?: string;
        "isValid"?: boolean;
        "onInputValueChanged"?: (event: YetiInputCustomEvent<CustomEvent>) => void;
        "onReadyToVerifyFast"?: (event: YetiInputCustomEvent<CustomEvent>) => void;
        "onReadyToVerifySlow"?: (event: YetiInputCustomEvent<CustomEvent>) => void;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "yeti-field": YetiField;
        "yeti-form-field": YetiFormField;
        "yeti-input": YetiInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "yeti-field": LocalJSX.YetiField & JSXBase.HTMLAttributes<HTMLYetiFieldElement>;
            "yeti-form-field": LocalJSX.YetiFormField & JSXBase.HTMLAttributes<HTMLYetiFormFieldElement>;
            "yeti-input": LocalJSX.YetiInput & JSXBase.HTMLAttributes<HTMLYetiInputElement>;
        }
    }
}
